version: '3.8'

services:
  mcp-bigquery-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    volumes:
      # Optional: mount credentials file if using file-based auth
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/app/credentials.json:ro
    command: >
      python -m src.mcp_bigquery_server.main 
      --project-id ${GOOGLE_CLOUD_PROJECT} 
      --http 
      --host 0.0.0.0 
      --port 8000
      ${GOOGLE_APPLICATION_CREDENTIALS:+--key-file /app/credentials.json}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
